apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: vinyl-postgres
spec:
  instances: 1
  postgresVersion: '13.3'
  pods:
    persistentVolume:
      size: '10Gi'
  configurations:
    postgres:
      default:
    pgBouncer:
      default:
