apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinyl-audio-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vinyl-audio-analyzer
  template:
    metadata:
      labels:
        app: vinyl-audio-analyzer
    spec:
      containers:
      - name: vinyl-audio-analyzer
        image: {{ .Values.image.repository }}-audio-analyzer:{{ .Values.image.tag }}
        ports:
        - containerPort: 5000
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      nodeSelector:
        kubernetes.io/hostname: knode
