apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinyl-postgres  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vinyl-postgres
  template:
    metadata:
      labels:
        app: vinyl-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: vinyl-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: vinyl-postgres-pv-claim-v2
      nodeSelector:
        kubernetes.io/hostname: knode