"""id number unique

Revision ID: 0b5c05669fb4
Revises: acb09fe4d7c4
Create Date: 2024-01-26 14:08:06.110635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5c05669fb4'
down_revision = 'acb09fe4d7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'release', ['id_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'release', type_='unique')
    # ### end Alembic commands ###
