"""add release purchased at

Revision ID: 45fd72c4fb31
Revises: 83e7ec2f24dd
Create Date: 2024-01-16 16:28:40.096194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fd72c4fb31'
down_revision = '83e7ec2f24dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('purchased_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'purchased_at')
    # ### end Alembic commands ###
