"""add release fields

Revision ID: 6ba57c3cca7f
Revises: 139e68b51a21
Create Date: 2023-12-21 10:09:37.203482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba57c3cca7f'
down_revision = '139e68b51a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('track', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('track', sa.Column('bpm', sa.Integer(), nullable=True))
    op.add_column('track', sa.Column('key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'key')
    op.drop_column('track', 'bpm')
    op.drop_column('track', 'genre')
    op.drop_column('release', 'notes')
    # ### end Alembic commands ###
