"""add release attributes

Revision ID: 83e7ec2f24dd
Revises: 855cba5c0cc5
Create Date: 2024-01-16 16:25:59.308072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e7ec2f24dd'
down_revision = '855cba5c0cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('thumb', sa.String(), nullable=True))
    op.add_column('release', sa.Column('year', sa.String(), nullable=True))
    op.add_column('release', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('release', sa.Column('styles', sa.String(), nullable=True))
    op.add_column('release', sa.Column('format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'format')
    op.drop_column('release', 'styles')
    op.drop_column('release', 'genre')
    op.drop_column('release', 'year')
    op.drop_column('release', 'thumb')
    # ### end Alembic commands ###
