"""add release track audio

Revision ID: 8ab544edb3a5
Revises: 6ba57c3cca7f
Create Date: 2023-12-22 09:50:25.148852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab544edb3a5'
down_revision = '6ba57c3cca7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('audio', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'audio')
    # ### end Alembic commands ###
