"""move audio to track

Revision ID: e5da33c19faa
Revises: 8ab544edb3a5
Create Date: 2023-12-23 11:07:22.941666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5da33c19faa'
down_revision = '8ab544edb3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('release', 'audio')
    op.add_column('track', sa.Column('audio', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'audio')
    op.add_column('release', sa.Column('audio', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
