apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vinyl-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: vinyl-manager.home.timosur.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: vinyl-backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vinyl-frontend
            port:
              number: 3000
