apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinyl-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vinyl-backend
  template:
    metadata:
      labels:
        app: vinyl-backend
    spec:
      containers:
      - name: vinyl-backend
        image: {{ .Values.image.repository }}-backend:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: vinyl-postgres-binding
              key: uri
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: vinyl-backend-secret
              key: secret_key
        - name: DISCOGS_USER_TOKEN
          valueFrom:
            secretKeyRef:
              name: vinyl-backend-secret
              key: discogs_user_token
        - name: AUDIO_ANALYZER_URL
          value: "http://vinyl-audio-analyzer.{{ .Release.Namespace }}.svc.cluster.local:8000"
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      nodeSelector:
        kubernetes.io/hostname: knode
