apiVersion: v1
kind: Secret
metadata:
  name: vinyl-backend-secret
type: Opaque
data:
  secret_key: {{ .Values.backend.secretKey | b64enc }}
  discogs_user_token: {{ .Values.backend.disogsUserToken | b64enc }}