apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinyl-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vinyl-frontend
  template:
    metadata:
      labels:
        app: vinyl-frontend
    spec:
      containers:
      - name: vinyl-frontend
        image: {{ .Values.image.repository }}-frontend:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          value: "http://vinyl-backend.{{ .Release.Namespace }}.svc.cluster.local:8080"
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      nodeSelector:
        kubernetes.io/hostname: knode
